"use client";
import { Box, Flex, Image, Text } from "@chakra-ui/react";
import Head from "next/head";

import AppFooter from "@/components/layout/AppFooter";
import LandingLayout from "@/components/layout/LandingLayout";

export default function Home() {
  return (
    <LandingLayout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box>
        <Box bg={"#F5F4FE"}>
          <Box pt={["100px", "200px", "300px"]}>
            <Text textAlign="center" variant={"h1"}>
              How it works
            </Text>
            <Text
              sx={{
                textAlign: "center",
                px: [4],
              }}
            >
              Stable++ issues $USDPP, a decentralized, over-collateralized stablecoin for RGB++ and Bitcoin ecosystem.
            </Text>
            <Flex
              flexDirection={"column"}
              alignItems="center"
              height={["310px", "310px", "410px"]}
              mt={["100px", "200px", "300px"]}
              position="relative"
            >
              <Box
                sx={{
                  position: "absolute",
                  left: -200,
                  right: -200,
                  top: 0,
                  bottom: 0,
                  transform: "rotate(-10deg)",
                  bgImage: "/img/landing/work-bg.png",
                  backgroundSize: "100% 100%",
                }}
              />
              <Image
                alt="thumb"
                position="absolute"
                top={["-100px", "-100px", "-260px"]}
                src="/img/landing/work-thumb.svg"
              />
              <Text
                sx={{
                  w: ["100%", "400px"],
                  px: [4],
                  color: "#fff",
                  position: "absolute",
                  bottom: ["50px", "100px"],
                }}
              >
                Collateralize $BTC and $CKB, mint $USDPP, the stablecoin that can freely flow in the Bitcoin ecosystem
                via RGB++.
              </Text>
            </Flex>
          </Box>

          <Box mt={["100px", "200px", "300px"]}>
            <Flex px={5} pb={["100px", "200px", "300px"]} flexDirection={"column"} alignItems="center">
              <Text variant={"h1"}>Partners</Text>
              <Text textAlign="center">Our trusted partners and investors</Text>
              <Flex
                sx={{
                  mt: 95,
                  flexDirection: ["column", "column", "row"],
                  justifyContent: "center",
                  alignItems: "center",
                  gap: [90, 90, 188],
                }}
              >
                <Image w={["200px", "200px", "auto"]} alt="partners" src="/img/landing/partners-1.svg" />
              </Flex>
              <Flex
                sx={{
                  justifyContent: "space-between",
                  alignItems: "center",
                  bgImage: "url(/img/landing/partners-bg.png)",
                  backgroundSize: "100% 100%",
                  width: ["100%", "100%", "100%", "100%", "1280px"],
                  flexDirection: ["column", "column", "column", "row", "row"],
                  gap: 5,
                  borderRadius: 14,
                  p: 6,
                  mt: ["100px", "150px", "260px"],
                }}
              >
                <Image src="/img/common/logo.svg" alt="logo" />
                <Text
                  sx={{
                    fontWeight: "500",
                    fontSize: 14,
                    maxWidth: 570,
                    textAlign: ["center", "center", "right"],
                    fontFamily: "Inter",
                  }}
                >
                  At Stable++, our vision is to unleash the liquidity of Bitcoin ecosystem and bootstrap DeFi use cases
                  on RGB++.
                </Text>
              </Flex>
            </Flex>
            <Box sx={{ position: "absolute", bottom: 0, right: 0, left: 0 }}>
              <AppFooter />
            </Box>
          </Box>
        </Box>
      </Box>
    </LandingLayout>
  );
}
